<?php

return [

    /*
    |--------------------------------------------------------------------------
    | Wołacz imion — słownik zamknięty
    |--------------------------------------------------------------------------
    |
    | Klucz = imię w mianowniku, małymi literami (porównanie przez mb_strtolower).
    | Wartość = wołacz w formie GOTOWEJ DO WYŚWIETLENIA, z wielkiej litery.
    |
    | Dlaczego słownik, a nie reguły: polski wołacz ma reguły, ale wyjątki trafiają
    | w najpopularniejsze imiona. „Ola" i „Kamila" kończą się tak samo na -la,
    | a mają różny wołacz (Olu / Kamilo), bo pierwsze to zdrobnienie. „Marek" gubi
    | ruchome „e" (Marku), a „Paweł" gubi je gdzie indziej (Pawle). Żadna reguła
    | literowa tego nie rozstrzygnie — a lista jest skończona i zmienia się raz na
    | pokolenie, więc wpisanie jej ręcznie jest tańsze i pewniejsze niż algorytm.
    |
    | Dlaczego zamknięty: brak wpisu to NIE jest błąd do naprawienia — to sygnał
    | „nie wiem", na który Vocative::of() odpowiada zwrotem null, a szablon pisze
    | imię w mianowniku („Cześć Kevin"). Mianownik nigdy nie ośmiesza, więc lista
    | nie musi być kompletna: trafienie daje „wow", pudło daje poziom większości
    | sklepów. Zgadywanie dawałoby „Cześć Kevino" — dlatego nie zgadujemy.
    |
    | Stała biznesowa, nie sekret — dlatego w `config/` (FOUNDATION sek. 5).
    |
    | Imiona przymiotnikowe (Jerzy, Antoni, Cezary, Ignacy…) mają wołacz równy
    | mianownikowi. Są tu wpisane JAWNIE, mimo że fallback dałby ten sam wynik —
    | bo to poprawna odmiana, a nie brak wiedzy, i test ma prawo tego pilnować.
    |
    | POKRYCIE: 86,9% osób w rejestrze PESEL (`docs/*.csv`, imię pierwsze osób
    | żyjących). Reszta to niemal wyłącznie imiona wschodnie (Oleksandr, Tetiana,
    | Nataliia…) — łącznie ~2 mln osób, które ŚWIADOMIE zostają w mianowniku:
    | zapisy paszportowe nie odmieniają się sensownie („Cześć Nataliio"), a „Cześć
    | Oleksandr" jest w porządku. Polskie imiona są tu wyczerpane do poziomu szumu
    | — po ostatnim przeglądzie w całym rejestrze zostały tylko trzy nieujęte imiona
    | z polskimi diakrytykami powyżej 2000 osób, wszystkie dopisane. Innymi słowy:
    | te 13% to nie luka do nadrobienia, tylko celowa decyzja.
    |
    */

    // ─── Żeńskie: pełne ──────────────────────────────────────────────────────
    'ada' => 'Ado',
    'adela' => 'Adelo',
    'adriana' => 'Adriano',
    'adrianna' => 'Adrianno',
    'agata' => 'Agato',
    'agnieszka' => 'Agnieszko',
    'aldona' => 'Aldono',
    'aleksandra' => 'Aleksandro',
    'alfreda' => 'Alfredo',
    'alicja' => 'Alicjo',
    'alina' => 'Alino',
    'amelia' => 'Amelio',
    'anastazja' => 'Anastazjo',
    'andżelika' => 'Andżeliko',
    'aneta' => 'Aneto',
    'anetta' => 'Anetto',
    'angelika' => 'Angeliko',
    'aniela' => 'Anielo',
    'anita' => 'Anito',
    'anna' => 'Anno',
    'antonina' => 'Antonino',
    'apolonia' => 'Apolonio',
    'arleta' => 'Arleto',
    'aurelia' => 'Aurelio',
    'barbara' => 'Barbaro',
    'beata' => 'Beato',
    'berenika' => 'Bereniko',
    'bernadeta' => 'Bernadeto',
    'bernadetta' => 'Bernadetto',
    'bianka' => 'Bianko',
    'blanka' => 'Blanko',
    'bogna' => 'Bogno',
    'bogumiła' => 'Bogumiło',
    'bogusława' => 'Bogusławo',
    'bożena' => 'Bożeno',
    'bożenna' => 'Bożenno',
    'bronisława' => 'Bronisławo',
    'brygida' => 'Brygido',
    'cecylia' => 'Cecylio',
    'celina' => 'Celino',
    'czesława' => 'Czesławo',
    'dagmara' => 'Dagmaro',
    'daniela' => 'Danielo',
    'danuta' => 'Danuto',
    'daria' => 'Dario',
    'diana' => 'Diano',
    'dominika' => 'Dominiko',
    'donata' => 'Donato',
    'dorota' => 'Doroto',
    'edyta' => 'Edyto',
    'eleonora' => 'Eleonoro',
    'eliza' => 'Elizo',
    'elwira' => 'Elwiro',
    'elżbieta' => 'Elżbieto',
    'emilia' => 'Emilio',
    'estera' => 'Estero',
    'eugenia' => 'Eugenio',
    'ewa' => 'Ewo',
    'ewelina' => 'Ewelino',
    'felicja' => 'Felicjo',
    'franciszka' => 'Franciszko',
    'gabriela' => 'Gabrielo',
    'gaja' => 'Gajo',
    'genowefa' => 'Genowefo',
    'gertruda' => 'Gertrudo',
    'grażyna' => 'Grażyno',
    'halina' => 'Halino',
    'halszka' => 'Halszko',
    'hanna' => 'Hanno',
    'helena' => 'Heleno',
    'henryka' => 'Henryko',
    'honorata' => 'Honorato',
    'ida' => 'Ido',
    'iga' => 'Igo',
    'ilona' => 'Ilono',
    'inga' => 'Ingo',
    'irena' => 'Ireno',
    'irmina' => 'Irmino',
    'iwona' => 'Iwono',
    'izabela' => 'Izabelo',
    'izabella' => 'Izabello',
    'jadwiga' => 'Jadwigo',
    'jagoda' => 'Jagodo',
    'janina' => 'Janino',
    'jaśmina' => 'Jaśmino',
    'joanna' => 'Joanno',
    'jolanta' => 'Jolanto',
    'jowita' => 'Jowito',
    'józefa' => 'Józefo',
    'judyta' => 'Judyto',
    'julia' => 'Julio',
    'julianna' => 'Julianno',
    'julita' => 'Julito',
    'justyna' => 'Justyno',
    'kaja' => 'Kajo',
    'kalina' => 'Kalino',
    'kamila' => 'Kamilo',
    'karina' => 'Karino',
    'karolina' => 'Karolino',
    'katarzyna' => 'Katarzyno',
    'kazimiera' => 'Kazimiero',
    'kinga' => 'Kingo',
    'klara' => 'Klaro',
    'klaudia' => 'Klaudio',
    'kornelia' => 'Kornelio',
    'krystyna' => 'Krystyno',
    'laura' => 'Lauro',
    'lena' => 'Leno',
    'leokadia' => 'Leokadio',
    'lidia' => 'Lidio',
    'liliana' => 'Liliano',
    'lilianna' => 'Lilianno',
    'liwia' => 'Liwio',
    'longina' => 'Longino',
    'lucyna' => 'Lucyno',
    'ludmiła' => 'Ludmiło',
    'ludwika' => 'Ludwiko',
    'luiza' => 'Luizo',
    'łucja' => 'Łucjo',
    'magda' => 'Magdo',
    'magdalena' => 'Magdaleno',
    'maja' => 'Majo',
    'malwina' => 'Malwino',
    'małgorzata' => 'Małgorzato',
    'marcelina' => 'Marcelino',
    'maria' => 'Mario',
    'marianna' => 'Marianno',
    'marika' => 'Mariko',
    'mariola' => 'Mariolo',
    'marlena' => 'Marleno',
    'marta' => 'Marto',
    'martyna' => 'Martyno',
    'marzanna' => 'Marzanno',
    'marzena' => 'Marzeno',
    'marzenna' => 'Marzenno',
    'matylda' => 'Matyldo',
    'melania' => 'Melanio',
    'michalina' => 'Michalino',
    'mieczysława' => 'Mieczysławo',
    'milena' => 'Mileno',
    'mirosława' => 'Mirosławo',
    'monika' => 'Moniko',
    'nadia' => 'Nadio',
    'natalia' => 'Natalio',
    'natasza' => 'Nataszo',
    'nikola' => 'Nikolo',
    'nina' => 'Nino',
    'oliwia' => 'Oliwio',
    'otylia' => 'Otylio',
    'patrycja' => 'Patrycjo',
    'paula' => 'Paulo',
    'paulina' => 'Paulino',
    'pelagia' => 'Pelagio',
    'regina' => 'Regino',
    'renata' => 'Renato',
    'roksana' => 'Roksano',
    'romana' => 'Romano',
    'rozalia' => 'Rozalio',
    'róża' => 'Różo',
    'sabina' => 'Sabino',
    'sandra' => 'Sandro',
    'sara' => 'Saro',
    'sławomira' => 'Sławomiro',
    'stanisława' => 'Stanisławo',
    'stefania' => 'Stefanio',
    'sylwia' => 'Sylwio',
    'tamara' => 'Tamaro',
    'teresa' => 'Tereso',
    'urszula' => 'Urszulo',
    'violetta' => 'Violetto',
    'wacława' => 'Wacławo',
    'wanda' => 'Wando',
    'weronika' => 'Weroniko',
    'wiesława' => 'Wiesławo',
    'wiktoria' => 'Wiktorio',
    'wioleta' => 'Wioleto',
    'wioletta' => 'Wioletto',
    'władysława' => 'Władysławo',
    'zdzisława' => 'Zdzisławo',
    'zenona' => 'Zenono',
    'zofia' => 'Zofio',
    'zuzanna' => 'Zuzanno',
    'żaneta' => 'Żaneto',

    // ─── Żeńskie: zdrobnienia ────────────────────────────────────────────────
    // Rozjazd -o / -u nie wynika z końcówki: „Ola" → Olu, ale „Kamila" → Kamilo.
    // Zdrobnienia na -ka idą na -o (Anka → Anko), na -sia/-cia/-zia/-nia → -u.
    'ala' => 'Alu',
    'ania' => 'Aniu',
    'anka' => 'Anko',
    'asia' => 'Asiu',
    'aśka' => 'Aśko',
    'basia' => 'Basiu',
    'baśka' => 'Baśko',
    'beatka' => 'Beatko',
    'bogusia' => 'Bogusiu',
    'bożenka' => 'Bożenko',
    'danka' => 'Danko',
    'dorotka' => 'Dorotko',
    'dosia' => 'Dosiu',
    'ela' => 'Elu',
    'elka' => 'Elko',
    'ewka' => 'Ewko',
    'frania' => 'Franiu',
    'gosia' => 'Gosiu',
    'gośka' => 'Gośko',
    'grażynka' => 'Grażynko',
    'halinka' => 'Halinko',
    'hania' => 'Haniu',
    'iwonka' => 'Iwonko',
    'iza' => 'Izo',
    'jadzia' => 'Jadziu',
    'jagusia' => 'Jagusiu',
    'joasia' => 'Joasiu',
    'julcia' => 'Julciu',
    'kasia' => 'Kasiu',
    'kasieńka' => 'Kasieńko',
    'kaśka' => 'Kaśko',
    'kazia' => 'Kaziu',
    'krysia' => 'Krysiu',
    'ksenia' => 'Kseniu',
    'lidzia' => 'Lidziu',
    'lila' => 'Lilu',
    'lola' => 'Lolu',
    'madzia' => 'Madziu',
    'mania' => 'Maniu',
    'martusia' => 'Martusiu',
    'marysia' => 'Marysiu',
    'marysieńka' => 'Marysieńko',
    'michasia' => 'Michasiu',
    'misia' => 'Misiu',
    'monisia' => 'Monisiu',
    'nela' => 'Nelu',
    'ola' => 'Olu',
    'olka' => 'Olko',
    'pola' => 'Polu',
    'renia' => 'Reniu',
    'rózia' => 'Róziu',
    'sonia' => 'Soniu',
    'stasia' => 'Stasiu',
    'terenia' => 'Tereniu',
    'tosia' => 'Tosiu',
    'ula' => 'Ulu',
    'ulka' => 'Ulko',
    'wisia' => 'Wisiu',
    'zosia' => 'Zosiu',
    'zośka' => 'Zośko',
    'zuzia' => 'Zuziu',

    // ─── Męskie: pełne ───────────────────────────────────────────────────────
    'adam' => 'Adamie',
    'adrian' => 'Adrianie',
    'alan' => 'Alanie',
    'albert' => 'Albercie',
    'aleks' => 'Aleksie',
    'aleksander' => 'Aleksandrze',
    'alfons' => 'Alfonsie',
    'alfred' => 'Alfredzie',
    'alojzy' => 'Alojzy',
    'ambroży' => 'Ambroży',
    'andrzej' => 'Andrzeju',
    'antoni' => 'Antoni',
    'arkadiusz' => 'Arkadiuszu',
    'artur' => 'Arturze',
    'barnaba' => 'Barnabo',
    'bartłomiej' => 'Bartłomieju',
    'bartosz' => 'Bartoszu',
    'bazyli' => 'Bazyli',
    'benedykt' => 'Benedykcie',
    'bernard' => 'Bernardzie',
    'błażej' => 'Błażeju',
    'bogdan' => 'Bogdanie',
    'bogumił' => 'Bogumile',
    'bogusław' => 'Bogusławie',
    'bolesław' => 'Bolesławie',
    'borys' => 'Borysie',
    'bronisław' => 'Bronisławie',
    'cezary' => 'Cezary',
    'cyprian' => 'Cyprianie',
    'czesław' => 'Czesławie',
    'damian' => 'Damianie',
    'daniel' => 'Danielu',
    'dariusz' => 'Dariuszu',
    'dawid' => 'Dawidzie',
    'dominik' => 'Dominiku',
    'dorian' => 'Dorianie',
    'edmund' => 'Edmundzie',
    'edward' => 'Edwardzie',
    'emil' => 'Emilu',
    'ernest' => 'Erneście',
    'erwin' => 'Erwinie',
    'eryk' => 'Eryku',
    'eugeniusz' => 'Eugeniuszu',
    'fabian' => 'Fabianie',
    'feliks' => 'Feliksie',
    'ferdynand' => 'Ferdynandzie',
    'filip' => 'Filipie',
    'florian' => 'Florianie',
    'franciszek' => 'Franciszku',
    'gabriel' => 'Gabrielu',
    'gerard' => 'Gerardzie',
    'gerwazy' => 'Gerwazy',
    'gracjan' => 'Gracjanie',
    'grzegorz' => 'Grzegorzu',
    'gustaw' => 'Gustawie',
    'henryk' => 'Henryku',
    'hieronim' => 'Hieronimie',
    'hilary' => 'Hilary',
    'hubert' => 'Hubercie',
    'ignacy' => 'Ignacy',
    'igor' => 'Igorze',
    'ireneusz' => 'Ireneuszu',
    'jacek' => 'Jacku',
    'jakub' => 'Jakubie',
    'jan' => 'Janie',
    'janusz' => 'Januszu',
    'jaromir' => 'Jaromirze',
    'jarosław' => 'Jarosławie',
    'jerzy' => 'Jerzy',
    'jędrzej' => 'Jędrzeju',
    'joachim' => 'Joachimie',
    'józef' => 'Józefie',
    'julian' => 'Julianie',
    'juliusz' => 'Juliuszu',
    'kacper' => 'Kacprze',
    'kajetan' => 'Kajetanie',
    'kamil' => 'Kamilu',
    'karol' => 'Karolu',
    'kazimierz' => 'Kazimierzu',
    'klaudiusz' => 'Klaudiuszu',
    'konrad' => 'Konradzie',
    'konstanty' => 'Konstanty',
    'kordian' => 'Kordianie',
    'kornel' => 'Kornelu',
    'krystian' => 'Krystianie',
    'krzysztof' => 'Krzysztofie',
    'ksawery' => 'Ksawery',
    'lech' => 'Lechu',
    'lechosław' => 'Lechosławie',
    'leon' => 'Leonie',
    'leonard' => 'Leonardzie',
    'lesław' => 'Lesławie',
    'longin' => 'Longinie',
    'lubomir' => 'Lubomirze',
    'lucjan' => 'Lucjanie',
    'ludwik' => 'Ludwiku',
    'łukasz' => 'Łukaszu',
    'maciej' => 'Macieju',
    'maksymilian' => 'Maksymilianie',
    'marcel' => 'Marcelu',
    'marceli' => 'Marceli',
    'marcin' => 'Marcinie',
    'marek' => 'Marku',
    'marian' => 'Marianie',
    'mariusz' => 'Mariuszu',
    'mateusz' => 'Mateuszu',
    'michał' => 'Michale',
    'mieczysław' => 'Mieczysławie',
    'mieszko' => 'Mieszku',
    'mikołaj' => 'Mikołaju',
    'miłosz' => 'Miłoszu',
    'mirosław' => 'Mirosławie',
    'natan' => 'Natanie',
    'nataniel' => 'Natanielu',
    'nikodem' => 'Nikodemie',
    'norbert' => 'Norbercie',
    'olaf' => 'Olafie',
    'olgierd' => 'Olgierdzie',
    'oliwier' => 'Oliwierze',
    'oskar' => 'Oskarze',
    'patryk' => 'Patryku',
    'paweł' => 'Pawle',
    'piotr' => 'Piotrze',
    'przemysław' => 'Przemysławie',
    'radosław' => 'Radosławie',
    'rafał' => 'Rafale',
    'rajmund' => 'Rajmundzie',
    'remigiusz' => 'Remigiuszu',
    'robert' => 'Robercie',
    'roland' => 'Rolandzie',
    'roman' => 'Romanie',
    'romuald' => 'Romualdzie',
    'ryszard' => 'Ryszardzie',
    'samuel' => 'Samuelu',
    'sebastian' => 'Sebastianie',
    'seweryn' => 'Sewerynie',
    'sławomir' => 'Sławomirze',
    'stanisław' => 'Stanisławie',
    'stefan' => 'Stefanie',
    'sylwester' => 'Sylwestrze',
    'szczepan' => 'Szczepanie',
    'szymon' => 'Szymonie',
    'tadeusz' => 'Tadeuszu',
    'teodor' => 'Teodorze',
    'teofil' => 'Teofilu',
    'tobiasz' => 'Tobiaszu',
    'tomasz' => 'Tomaszu',
    'tymon' => 'Tymonie',
    'tymoteusz' => 'Tymoteuszu',
    'wacław' => 'Wacławie',
    'waldemar' => 'Waldemarze',
    'walenty' => 'Walenty',
    'wiesław' => 'Wiesławie',
    'wiktor' => 'Wiktorze',
    'wincenty' => 'Wincenty',
    'wit' => 'Wicie',
    'witold' => 'Witoldzie',
    'władysław' => 'Władysławie',
    'włodzimierz' => 'Włodzimierzu',
    'wojciech' => 'Wojciechu',
    'zbigniew' => 'Zbigniewie',
    'zdzisław' => 'Zdzisławie',
    'zenon' => 'Zenonie',
    'ziemowit' => 'Ziemowicie',
    'zygmunt' => 'Zygmuncie',

    // ─── Męskie: zdrobnienia ─────────────────────────────────────────────────
    // Ruchome „e" (Marek → Marku) plus palatalizacja (Maciek → Maćku). Dwa
    // niezależne procesy naraz — dlatego z listy, nie z reguły.
    'adaś' => 'Adasiu',
    'alek' => 'Alku',
    'antek' => 'Antku',
    'bartek' => 'Bartku',
    'bolek' => 'Bolku',
    'czarek' => 'Czarku',
    'darek' => 'Darku',
    'edek' => 'Edku',
    'franek' => 'Franku',
    'grzesiek' => 'Grześku',
    'grzesio' => 'Grzesiu',
    'heniek' => 'Heńku',
    'janek' => 'Janku',
    'jasiek' => 'Jaśku',
    'jaś' => 'Jasiu',
    'józek' => 'Józku',
    'kazek' => 'Kazku',
    'kazik' => 'Kaziku',
    'krzysiek' => 'Krzyśku',
    'kuba' => 'Kubo',
    'kubuś' => 'Kubusiu',
    'leszek' => 'Leszku',
    'lolek' => 'Lolku',
    'maciek' => 'Maćku',
    'marcinek' => 'Marcinku',
    'mietek' => 'Mietku',
    'mirek' => 'Mirku',
    'olek' => 'Olku',
    'piotrek' => 'Piotrku',
    'przemek' => 'Przemku',
    'radek' => 'Radku',
    'romek' => 'Romku',
    'rysiek' => 'Ryśku',
    'sławek' => 'Sławku',
    'staś' => 'Stasiu',
    'stasiek' => 'Staśku',
    'tadek' => 'Tadku',
    'tomek' => 'Tomku',
    'wicek' => 'Wicku',
    'wiesiek' => 'Wieśku',
    'władek' => 'Władku',
    'wojtek' => 'Wojtku',
    'zbyszek' => 'Zbyszku',
    'zdzisiek' => 'Zdziśku',
    'zenek' => 'Zenku',

];
